version: '3.7'
services:
  # db:
  #   image: 'postgres:latest'
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: raghavgandhi
  #     POSTGRES_PASSWORD: apple
  #     POSTGRES_DB: price_alert_app_development
  #   ports:
  #     - "5432:5432"
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   command: redis-server
  # redis:
  #   image: redis
  #   volumes:
  #     - ~/redis-data:/data
  # postgres:
  #   image: postgis/postgis:13-3.2-alpine
  #   volumes:
  #     - ~/postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: raghavgandhi
  #     POSTGRES_PASSWORD: apple
  #     POSTGRES_DB: price_alert_app_development
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=raghavgandhi
      - POSTGRES_PASSWORD=apple
      - POSTGRES_DB=price_alert_app_development

  redis:
    image: redis:alpine
    restart: always
    ports:
     - 6379:6379
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/price_alert_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/price_alert_app

volumes:
  db_data: {}
  redis_data: {}