default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # username: raghavgandhi
  # password: apple
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: price_alert_app_development

test:
  <<: *default
  database: price_alert_app_test

production:
  <<: *default
  database: price_alert_app_production
  username: raghavgandhi
  password: apple
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
