default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: postgres
  username: raghavgandhi
  password: apple
  port: 5432

development:
  <<: *default
  database: price_alert_app_development

test:
  <<: *default
  database: price_alert_app_test

production:
  <<: *default
  database: price_alert_app_production
  username: raghavgandhi
  password: apple
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
